### ISSUE TITLE
Explicit the Node.js minimum version dependency (v16?)

### ISSUE THREAD

**Issue by WilliamRaphaWyde** [wynsure/script.cli#13]
With recent changes, script.cli is not compatible with Node 14 anymore, it requires Node 16 or a more recent version.

The below code:

https://github.com/wynsure/script.cli/blame/bfe9ccaecd3bdac66421affaae08b781b4296824/src/db.ts#L165-L168

- is not working with Node 14.21.3 which uses the V8 Javascript engine version 8.4.371.23-node.88
- is working with Node 16.20.2 which uses the V8 Javascript engine version 9.4.146.26-node.26

![image](https://github.com/wynsure/script.cli/assets/55548823/6b1b2b5f-0119-4c0a-8317-20806d87ba62)

Root cause seems to be the V8 engine version which added the at() method on array in version 9.2:

https://v8.dev/blog/v8-release-92#javascript

I suggest adding an "engines" section in package.json to make the dependency explicit.

cf. for example:

- [WynsureEnvRoot](https://github.com/MphasisWyde/WynsureEnvRoot/blob/Dev/package.json#L216-L218)
- [node-hosting](https://github.com/MphasisWyde/ewam-kernel/blob/32f8a0a1347bd57c1ebb2b76ca72add1124adae7/Packages/ewam-node-hosting/package.cmake.json#L9-L11)

**Comment by JeromeCugny** [comment]
thank you, nice debugging
